import colorama
from colorama import Fore

# help(colorama)

print(f"name {colorama.__name__}")
print(f"type {type(colorama)}")
print(f"dir {dir(colorama)}")
print(f"callable: {callable(colorama)}")
print("Installation: pip install colorama OR conda install -c anaconda colorama")
print("Colorama arguments: Back, Cursor, Fore, Style")
print("from colorama import [argument] - required to import an argument")
print("Can be separated by commas: from colorama import Fore, Back")
print("Example: from colorama import Fore - provides argument Fore")
print("import colorama - does not provide arguments")
print("Colorama init:")
print("colorama.init()")
print("colorama.deinit()")
print("colorama.reinit()")
print("colorama.init(autoreset=True) - style will be reset automatically")
print("Text coloring: print([argument] + [text])")
print("Reset argument: STYLE.RESET_ALL")
print("Example:")
print("print(Fore.RED + 'RED TEXT' - red foreground (text)")
print("print(STYLE.RESET_ALL) - reset")
print("The arguments must be uppercase")
print("Example:")
colorama.init(autoreset=True)
print(Fore.GREEN + "Green text")
print(Fore.RED + "Red text")
print("Normal text")
while True:
    find = input('find:')
    print(f"Found: {hasattr(colorama, find)}")
    print(f"Attribute: {getattr(colorama, find, None)}")
    print(f"Callable: {callable(find)}")
